# data_root_dir = '/Volumes/data/lupe'
data_root_dir = '/Users/justinjames/LUPE_Corder-Lab'

###### DO NOT CHANGE ANYTHING BELOW ######
behavior_names = ['still',
                  'walking',
                  'rearing',
                  'grooming',
                  'licking hindpaw L',
                  'licking hindpaw R']

behavior_colors = ['crimson',
                   'darkcyan',
                   'goldenrod',
                   'royalblue',
                   'rebeccapurple',
                   'mediumorchid']

keypoints = ["nose", "mouth", "l_forepaw", "l_forepaw_digit", "r_forepaw", "r_forepaw_digit",
             "l_hindpaw", "l_hindpaw_digit1", "l_hindpaw_digit2", "l_hindpaw_digit3",
             "l_hindpaw_digit4", "l_hindpaw_digit5", "r_hindpaw", "r_hindpaw_digit1",
             "r_hindpaw_digit2", "r_hindpaw_digit3", "r_hindpaw_digit4", "r_hindpaw_digit5",
             "genitalia", "tail_base"]

# 30 pixels = 1 cm
pixel_cm = 0.0330828

sexes = ['Male', 'Female']
drugs_study5 = ['Morphine', 'Morphine_Formalin']

groups = [f'Group{i}' for i in range(1, 8)]
groups_sni = ['A_Baseline_NoSNI', 'B_Baseline_SNI', 'C_3ISNI_DCZ', 'D_4WSNI_DCZ']
groups_raquel = ['D1', 'D3', 'D7', 'D14', 'D21']
groups_study4 = ['Male', 'Female', 'Combined']
groups_study5 = ['Male', 'Female', 'Combined']
groups_study6 = ['Male', 'Female', 'Combined']
groups_sni_sex = ['A_Baseline_NoSNI', 'B_Baseline_SNI', 'C_3WSNI_DCZ', 'D_4WSNI_DCZ']
groups_sni_combined = ['A_Baseline_NoSNI', 'B_Baseline_SNI', 'C_3WSNI_DCZ', 'D_4WSNI_DCZ']
groups_lmw_mor_reexpression = ['Male', 'Female', 'Combined']
groups_lle_rILN = ['Group1_SNI','Group2_Uninjured-Formalin']
groups_cso_sar_miniscope = ['M1','M3']

conditions = [f'Condition{i}' for i in range(1, 4)]
conditions_extra = ['Condition3A', 'Condition3B']
conditions_hab = ['HAB_D1_Male', 'HAB_D1_Female', 'HAB_D2_Male', 'HAB_D2_Female']
conditions_raquel = ['Control', 'Experimental']
conditions_study4 = ['Control', 'Experimental']
conditions_study5 = ['Control', 'Experimental']
conditions_study6 = ['Control', 'Experimental']
conditions_sni_sex = ['control_mMORP-eYFP_MALE', 'control_mMORP-eYFP_FEMALE', 'exp_mMORP-hm4di_MALE', 'exp_mMORP-hm4di_FEMALE']
conditions_sni_combined = ['control_mMORP-eYFP', 'exp_mMORP-hm4di']
conditions_lmw_mor_reexpression = ['Control', 'Exp_MOR-ko']
conditions_lle_rILN = ['rILN_eYFP','rILN_hm4Di']
conditions_cso_sar_miniscope = ['baseline','cap','morphine','morphine-capsaicin']

groups_noci_morp_dreadd = ['Combined', 'Female', 'Male']
conditions_noci_morp_dreadd = ['EXP_CONFON', 'EXP_MORP', 'EXP_YFP']

groups_bla_sni_opto_inhibit = ['SNI', 'NoSNI']
conditions_bla_sni_opto_inhibit = ['CTRL_FLEX', 'EXP_stGtACR2_inhibit']
groups_project_cso_capsaicin2ug = ['M1', 'M2', 'M3', 'M4']
conditions_project_cso_capsaicin2ug = ['baseline', 'test_2ug']
groups_project_SAR_PsiloRSC = ['Pre_PsiloInjection', 'Post_PsiloInjection']
conditions_project_SAR_PsiloRSC = ['M1', 'M2', 'M3']
groups_project_LLE_rILNMORDREADD = ['Group1_SNI']
conditions_project_LLE_rILNMORDREADD = ['rILN_eYFP_M30', 'rILN_eYFP_M30_0', 'rILN_eYFP_M30_1', 'rILN_eYFP_M30_2', 'rILN_eYFP_M31_1', 'rILN_hm4Di_M28_0', 'rILN_hm4Di_M28_1', 'rILN_hm4Di_M28_2', 'rILN_hm4Di_M28_3', 'rILN_hm4Di_M29_0', 'rILN_hm4Di_M29_1', 'rILN_hm4Di_M29_2']
groups_project_CSO_FormalinMiniscope = ['SalineFormalin', 'MorphineFormalin']
conditions_project_CSO_FormalinMiniscope = ['M1', 'M2', 'M3']
groups_project_LLE_rILNMORDREADD_Group1SNI = ['Group1_SNI']
conditions_project_LLE_rILNMORDREADD_Group1SNI = ['rILN_eYFP_M30', 'rILN_eYFP_M30_0', 'rILN_eYFP_M30_1', 'rILN_eYFP_M30_2', 'rILN_eYFP_M31_1', 'rILN_hm4Di_M28_0', 'rILN_hm4Di_M28_1', 'rILN_hm4Di_M28_2', 'rILN_hm4Di_M28_3', 'rILN_hm4Di_M29_0', 'rILN_hm4Di_M29_1', 'rILN_hm4Di_M29_2']
groups_project_LLE_rILNMORDREADD_Group2UninjuredFormalin = ['Group2_UninjuredFormalin']
conditions_project_LLE_rILNMORDREADD_Group2UninjuredFormalin = ['rILN_hm4Di_M24_2', 'rILN_hm4Di_M24_1', 'rILN_hm4Di_M24_0', 'rILN_hm4Di_M24', 'rILN_eYFP_M26_3', 'rILN_eYFP_M26_2', 'rILN_eYFP_M26_1', 'rILN_eYFP_M26_0', 'rILN_eYFP_M26']
groups_project_CSO_FormalinMiniscopeSegmented = ['SalineFormalin', 'MorphineFormalin']
conditions_project_CSO_FormalinMiniscopeSegmented = ['M1', 'M2', 'M3']
groups_project_lindsay_PsiloSNI_cohort = ['1_BL', '2_30Min', '3_24Hr', '4_7Days']
conditions_project_lindsay_PsiloSNI_cohort = ['SNI_Saline', 'Uninjured_Psilo', 'SNI_Psilo', 'Uninjured_Saline']
groups_project_SP_ProglumideSNI = ['NoInjury', 'SNI']
conditions_project_SP_ProglumideSNI = ['Male', 'Female']
groups_project_SP_ProglumideSNI_cohort = ['NoInjury', 'SNI']
conditions_project_SP_ProglumideSNI_cohort = ['Combined']
groups_project_SP_ProglumideSalineSNI = ['NoInjury', 'SNI']
conditions_project_SP_ProglumideSalineSNI = ['Saline', 'Proglumide']
groups_project_SP_ProglumideFormalin = ['Saline', 'Proglumide']
conditions_project_SP_ProglumideFormalin = ['Male', 'Female', 'Combined']
groups_project_ACC_MiniscopeSNI_Baseline = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Baseline = ['Combined']
groups_project_ACC_MiniscopeSNI_OneHr = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_OneHr = ['Combined']
groups_project_ACC_MiniscopeCapsaicin = ['M1', 'M3']
conditions_project_ACC_MiniscopeCapsaicin = ['baseline', 'cap', 'morphine', 'morphine-capsaicin']
groups_project_ACC_MiniscopeSNI = ['Baseline', 'SNI_1Hr', 'SNI_24Hr', 'SNI_72Hr', 'SNI_1Week', 'SNI_2Week', 'SNI_3Week', 'SNI_3WeekMorphine']
conditions_project_ACC_MiniscopeSNI = ['NoInjury', 'SNI']
groups_project_ACC_MiniscopeSNI_24Hr = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_24Hr = ['Combined']
groups_project_ACC_MiniscopeSNI_72Hr = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_72Hr = ['Combined']
groups_project_ACC_MiniscopeSNI_1Week = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_1Week = ['Combined']
groups_project_ACC_MiniscopeSNI_2Week = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_2Week = ['Combined']
groups_project_ACC_MiniscopeSNI_3Week = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_3Week = ['Combined']
groups_project_ACC_MiniscopeSNI_3WeekMorphine = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_3WeekMorphine = ['Combined']
groups_project_SP_Proglumide1Formalin = ['Saline', 'Proglumide']
conditions_project_SP_Proglumide1Formalin = ['Male', 'Female', 'Combined']
groups_project_ACC_MiniscopeSNI_Sucrose = ['Combined']
conditions_project_ACC_MiniscopeSNI_Sucrose = ['CSO18', 'MM103', 'MM104', 'MM105']
groups_project_SP_DoxRMA1Formalin = ['Male', 'Female', 'Combined']
conditions_project_SP_DoxRMA1Formalin = ['Uninjured', 'Formalin']
groups_project_ACC_MiniscopeSNI_5Week = ['Combined']
conditions_project_ACC_MiniscopeSNI_5Week = ['CSO15', 'CSO17', 'CSO19', 'MM98']
groups_project_ACC_MiniscopeSNI_5WeekPsilo = ['Combined']
conditions_project_ACC_MiniscopeSNI_5WeekPsilo = ['CSO15', 'CSO17', 'CSO19', 'MM98']
groups_project_ACC_MiniscopeSNI_5Week24HrPsilo = ['Combined']
conditions_project_ACC_MiniscopeSNI_5Week24HrPsilo = ['CSO15', 'CSO17', 'MM98']
groups_project_ACC_MiniscopeSNI_Female_Baseline = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_Baseline = ['Combined']
groups_project_ACC_MiniscopeSNI_Female_1Hr = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_1Hr = ['Combined']
groups_project_ACC_MiniscopeSNI_Female = ['Baseline', 'SNI_1Hr', 'SNI_1Week', 'SNI_2Week', 'SNI_3Week', 'SNI_3WeekMorphine']
conditions_project_ACC_MiniscopeSNI_Female = ['NoInjury', 'SNI']
groups_project_ACC_MiniscopeSNI_Female_24Hr = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_24Hr = ['Combined']
groups_project_ACC_MiniscopeSNI_Male_Psilo_1Week = ['Combined']
conditions_project_ACC_MiniscopeSNI_Male_Psilo_1Week = ['CSO15', 'CSO17', 'CSO19', 'MM98']
groups_project_ACC_MiniscopeSNI_Female_72Hr = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_72Hr = ['Combined']
groups_project_ACC_MiniscopeSNI_Female_1Week = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_1Week = ['Combined']
groups_project_ACC_MorphineResponse = ['Male', 'Female']
conditions_project_ACC_MorphineResponse = ['Group1_0mgkg', 'Group2_0.5mgkg', 'Group3_1.0mgkg', 'Group4_5mgkg', 'Group5_10mgkg']
groups_project_ACC_Condition1_MorphineResponse = ['Male', 'Female']
conditions_project_ACC_Condition1_MorphineResponse = ['Group1_0mgkg', 'Group2_0.5mgkg', 'Group3_1.0mgkg', 'Group4_5mgkg', 'Group5_10mgkg']
groups_project_ACC_Study1_MorphineResponse = ['Male', 'Female']
conditions_project_ACC_Study1_MorphineResponse = ['Group1_0mgkg', 'Group2_0.5mgkg', 'Group3_1.0mgkg', 'Group4_5mgkg', 'Group5_10mgkg']
groups_project_ACC_Study2_CapsaicinMorphine = ['Male', 'Female']
conditions_project_ACC_Study2_CapsaicinMorphine = ['Group1_0mgkg', 'Group2_0.5mgkg', 'Group3_1.0mgkg', 'Group4_5mgkg', 'Group5_10mgkg']
groups_project_ACC_Study3_FormalinMorphine = ['Male', 'Female']
conditions_project_ACC_Study3_FormalinMorphine = ['Group1_0mgkg', 'Group2_0.5mgkg', 'Group3_1.0mgkg', 'Group4_5mgkg', 'Group5_10mgkg']
groups_project_ACC_MORPDreadd = ['A_Baseline_NoSNI', 'B_Baseline_SNI', 'C_3WSNI_DCZ', 'D_4WSNI_DCZ']
conditions_project_ACC_MORPDreadd = ['Condition1_mMORPhm4di_Male', 'Condition2_mMORPhm4di_Female', 'Condition3_mMORPeYFP']
groups_project_ACC_Study4_NociFormalinResponse = ['Male', 'Female']
conditions_project_ACC_Study4_NociFormalinResponse = ['Group6_1PerFormalin', 'Group7_5PerFormalin']
groups_project_ACC_oprm1KO = ['Control_OPRM1_flfl-GFP', 'Exp_OPRM1_flfl-hsyn-cre-GFP']
conditions_project_ACC_oprm1KO = ['Combined']
groups_project_ACC_oprm1Rexpress = ['Condition1_morphine-alone', 'Condition2_morphine-formalin']
conditions_project_ACC_oprm1Rexpress = ['CONTROL_eYFP_COMBINED', 'EXPERIMENT_MOR_COMBINED']
groups_project_ACC_MiniscopeSNI_Female_2Week = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_2Week = ['Combined']
groups_project_ACC_MORPDreadd_Combined = ['A_Baseline_NoSNI', 'B_Baseline_SNI', 'C_3WSNI_DCZ', 'D_4WSNI_DCZ']
conditions_project_ACC_MORPDreadd_Combined = ['Exp_mMORPhm4di', 'Control_mMORPeYFP']
groups_project_ACC_MiniscopeSNI_Female_3Week = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_3Week = ['Combined']
groups_project_ACC_MiniscopeSNI_Female_3WeekMorphine = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_3WeekMorphine = ['Combined']
groups_project_ACC_NociMorpDreadd_Formalin = ['Combined', 'Male', 'Female']
conditions_project_ACC_NociMorpDreadd_Formalin = ['EXP_YFP', 'EXP_CONFON', 'EXP_MORP']
groups_project_ACC_MiniscopeSNI_Male_3Month = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Male_3Month = ['Combined']
groups_project_ACC_MiniscopeSNI_Male_3MonthPsilo = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Male_3MonthPsilo = ['Combined']
groups_project_ACC_MiniscopeSNI_Male_3MonthPsilo24Hrs = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Male_3MonthPsilo24Hrs = ['Combined']
groups_project_ACC_MiniscopeSNI_Female_3Month = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_3Month = ['Combined']
groups_project_ACC_MiniscopeSNI_Female_3MonthPsilo = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_3MonthPsilo = ['Combined']
groups_project_ACC_MiniscopeSNI_Female_3MonthPsilo24Hrs = ['NoInjury', 'SNI']
conditions_project_ACC_MiniscopeSNI_Female_3MonthPsilo24Hrs = ['Combined']
groups_project_model_Formalin_RightHP = ['Male', 'Female']
conditions_project_model_Formalin_RightHP = ['Combined']
groups_project_model_SNI_RightHP_Baseline = ['Male', 'Female']
conditions_project_model_SNI_RightHP_Baseline = ['Combined']
groups_project_LUPE_sleepmodel = ['Combined']
conditions_project_LUPE_sleepmodel = ['Seg1', 'Seg2']
